Analysis Assignment

Part 1: Setup

The first thing I did was load both datasets and immediately check their shape. Both came back as 740 rows which confirmed straight away that they shared the same structure and could be joined on the ID column.

In [1]:
import pandas as pd

df         = pd.read_csv(r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\Absenteeism_at_work.csv")
df_survey  = pd.read_csv(r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\Happiness_Index.csv")

print('Absenteeism data: ', df.shape[0], 'rows,', df.shape[1], 'columns')
print('Survey data:      ', df_survey.shape[0], 'rows,', df_survey.shape[1], 'columns')

Absenteeism data:  740 rows, 24 columns
Survey data:       740 rows, 6 columns

Part 2: Viewing the data

Before doing anything else I ran head(), dtypes, and describe() on both files. This gave me a quick sense of what I was working with. I noticed Transportation expense was stored as an object instead of a number, which told me there was likely a formatting issue in that column I'd need to fix.

In [2]:
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Birth date,...,Education,Children,Drinker,Smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours,class
0,4,0,0,3,1,118,14,13,40,3/30/78,...,1,1,1,0,8,98,170,34,0,0
1,8,0,0,4,2,231,35,14,39,3/30/79,...,1,2,1,0,2,100,170,35,0,0
2,35,0,0,6,3,179,45,14,53,4/2/65,...,1,1,0,0,1,77,175,25,0,0
3,27,23,1,5,2,184,42,7,27,3/27/91,...,1,0,0,0,0,58,167,21,2,0
4,27,23,1,5,2,184,42,7,27,3/27/91,...,1,0,0,0,0,58,167,21,2,0

In [3]:
print(df.dtypes)

ID                                  int64
Reason for absence                  int64
Month of absence                    int64
Day of the week                     int64
Seasons                             int64
Transportation expense             object
Distance from Residence to Work     int64
Service time                        int64
Age                                 int64
Birth date                         object
Hire date                          object
Work load Average/day               int64
Hit target                          int64
Disciplinary failure                int64
Education                           int64
Children                            int64
Drinker                             int64
Smoker                              int64
Pet                                 int64
Weight                              int64
Height                              int64
Body mass index                     int64
Absenteeism time in hours           int64
class                               int64
dtype: object

In [4]:
print(df.isnull().sum())

ID                                 0
Reason for absence                 0
Month of absence                   0
Day of the week                    0
Seasons                            0
Transportation expense             0
Distance from Residence to Work    0
Service time                       0
Age                                0
Birth date                         0
Hire date                          0
Work load Average/day              0
Hit target                         0
Disciplinary failure               0
Education                          0
Children                           0
Drinker                            0
Smoker                             0
Pet                                0
Weight                             0
Height                             0
Body mass index                    0
Absenteeism time in hours          0
class                              0
dtype: int64

In [5]:
df.describe().round(2)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,...,Education,Children,Drinker,Smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours,class
count,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00,...,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00,740.00
mean,18.02,19.22,7.36,3.91,2.55,29.63,12.55,36.45,271895.64,94.59,...,1.29,1.02,0.57,0.07,0.75,79.04,172.11,26.68,6.92,0.37
std,11.02,8.43,3.15,1.42,1.11,14.84,4.38,6.48,40895.04,3.78,...,0.67,1.10,0.50,0.26,1.32,12.88,6.03,4.29,13.33,0.48
min,1.00,0.00,0.00,2.00,1.00,5.00,1.00,27.00,205917.00,81.00,...,1.00,0.00,0.00,0.00,0.00,56.00,163.00,19.00,0.00,0.00
25%,9.00,13.00,5.00,3.00,2.00,16.00,9.00,31.00,244387.00,93.00,...,1.00,0.00,0.00,0.00,0.00,69.00,169.00,24.00,2.00,0.00
50%,18.00,23.00,7.00,4.00,3.00,26.00,13.00,37.00,264249.00,95.00,...,1.00,1.00,1.00,0.00,0.00,83.00,170.00,25.00,3.00,0.00
75%,28.00,26.00,10.00,5.00,4.00,50.00,16.00,40.00,294217.00,97.00,...,1.00,2.00,1.00,0.00,1.00,89.00,172.00,31.00,8.00,1.00
max,36.00,28.00,12.00,6.00,4.00,52.00,29.00,58.00,602585.00,100.00,...,4.00,4.00,1.00,1.00,8.00,108.00,196.00,38.00,120.00,1.00

In [6]:
df_survey.head()

,ID,Absenteeism time in hours,HI1_WorkSatisfaction,HI2_LikesManager,HI3_EnjoysColleagues,HI4_WantstoStay
0,4,0,2,5,2,2
1,8,0,3,2,2,5
2,35,0,2,4,3,1
3,27,2,1,4,3,2
4,27,2,2,5,3,1

In [7]:
print(df_survey.dtypes)

ID                           int64
Absenteeism time in hours    int64
HI1_WorkSatisfaction         int64
HI2_LikesManager             int64
HI3_EnjoysColleagues         int64
HI4_WantstoStay              int64
dtype: object

In [8]:
print(df_survey.isnull().sum())

ID                           0
Absenteeism time in hours    0
HI1_WorkSatisfaction         0
HI2_LikesManager             0
HI3_EnjoysColleagues         0
HI4_WantstoStay              0
dtype: int64

In [9]:
df_survey.describe().round(2)

,ID,Absenteeism time in hours,HI1_WorkSatisfaction,HI2_LikesManager,HI3_EnjoysColleagues,HI4_WantstoStay
count,740.00,740.00,740.00,740.00,740.00,740.00
mean,18.02,6.92,2.02,3.59,2.73,2.09
std,11.02,13.33,1.13,1.12,0.78,1.17
min,1.00,0.00,1.00,1.00,1.00,1.00
25%,9.00,2.00,1.00,3.00,2.00,1.00
50%,18.00,3.00,2.00,4.00,3.00,2.00
75%,28.00,8.00,2.00,4.00,3.00,2.00
max,36.00,120.00,5.00,5.00,5.00,5.00

Part 3: Cleaning Absentee Data

The raw data stored most categorical variables as numbers (day of week was 2 through 6, education was 1 through 4, absence reasons were 0 through 28). Those numbers are meaningless on their own and don't translate well into Tableau. So I created readable label columns by mapping each number to its actual meaning. For example 2 becomes Monday, 1 becomes High School, 23 becomes Medical Consultation. I kept the original numeric columns as well so I didn't lose anything.

I also fixed the Transportation expense column by stripping out commas and converting it to a proper numeric type. After cleaning I re-ran the null check and found 3 nulls in Month Name and 1 in Transportation expense. For Transportation expense I filled it with the median (I chose median over mean because it's more resistant to outliers). For Month Name the nulls came from records where Month of absence was 0, meaning it simply wasn't recorded, so I mapped those to 'Not Recorded' rather than dropping the rows.

In [10]:
df['Transportation expense'] = pd.to_numeric(
    df['Transportation expense'].astype(str).str.replace(',', '').str.strip(),
    errors='coerce'
)

df['Day Name'] = df['Day of the week'].map({
    2: 'Monday', 3: 'Tuesday', 4: 'Wednesday', 5: 'Thursday', 6: 'Friday'
})

df['Season Name'] = df['Seasons'].map({
    1: 'Summer', 2: 'Autumn', 3: 'Winter', 4: 'Spring'
})

df['Education Level'] = df['Education'].map({
    1: 'High School', 2: 'Graduate', 3: 'Postgraduate', 4: 'Master / Doctor'
})

df['Disciplinary Failure'] = df['Disciplinary failure'].map({1: 'Yes', 0: 'No'})

df['Is Drinker'] = df['Drinker'].map({1: 'Drinker',    0: 'Non-Drinker'})
df['Is Smoker']  = df['Smoker'].map( {1: 'Smoker',     0: 'Non-Smoker'})

df['Month Name'] = df['Month of absence'].map({
    1: 'January', 2: 'February', 3: 'March',     4: 'April',
    5: 'May',     6: 'June',     7: 'July',       8: 'August',
    9: 'September', 10: 'October', 11: 'November', 12: 'December'
})

df['Reason Label'] = df['Reason for absence'].map({
    0:  'Unknown',
    1:  'Infectious & Parasitic Diseases',
    2:  'Neoplasms',
    3:  'Blood & Immune Disorders',
    4:  'Endocrine & Metabolic Diseases',
    5:  'Mental & Behavioural Disorders',
    6:  'Diseases of the Nervous System',
    7:  'Diseases of the Eye',
    8:  'Diseases of the Ear',
    9:  'Circulatory Diseases',
    10: 'Respiratory Diseases',
    11: 'Digestive Diseases',
    12: 'Skin Diseases',
    13: 'Musculoskeletal Diseases',
    14: 'Genitourinary Diseases',
    15: 'Pregnancy & Childbirth',
    16: 'Perinatal Conditions',
    17: 'Congenital Malformations',
    18: 'Symptoms & Abnormal Findings',
    19: 'Injury & Poisoning',
    20: 'External Causes',
    21: 'Factors Influencing Health Status',
    22: 'Patient Follow-Up',
    23: 'Medical Consultation',
    24: 'Blood Donation',
    25: 'Laboratory Examination',
    26: 'Unjustified Absence',
    27: 'Physiotherapy',
    28: 'Dental Consultation'
})

label_cols = ['Day Name', 'Season Name', 'Month Name', 'Education Level',
              'Disciplinary Failure', 'Is Drinker', 'Is Smoker', 'Reason Label']
for col in label_cols:
    print(f'   {col}: {df[col].nunique()} unique values')

   Day Name: 5 unique values
   Season Name: 4 unique values
   Month Name: 12 unique values
   Education Level: 4 unique values
   Disciplinary Failure: 2 unique values
   Is Drinker: 2 unique values
   Is Smoker: 2 unique values
   Reason Label: 28 unique values

In [11]:
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Birth date,...,Absenteeism time in hours,class,Day Name,Season Name,Education Level,Disciplinary Failure,Is Drinker,Is Smoker,Month Name,Reason Label
0,4,0,0,3,1,118.0,14,13,40,3/30/78,...,0,0,Tuesday,Summer,High School,No,Drinker,Non-Smoker,NaN,Unknown
1,8,0,0,4,2,231.0,35,14,39,3/30/79,...,0,0,Wednesday,Autumn,High School,No,Drinker,Non-Smoker,NaN,Unknown
2,35,0,0,6,3,179.0,45,14,53,4/2/65,...,0,0,Friday,Winter,High School,No,Non-Drinker,Non-Smoker,NaN,Unknown
3,27,23,1,5,2,184.0,42,7,27,3/27/91,...,2,0,Thursday,Autumn,High School,No,Non-Drinker,Non-Smoker,January,Medical Consultation
4,27,23,1,5,2,184.0,42,7,27,3/27/91,...,2,0,Thursday,Autumn,High School,No,Non-Drinker,Non-Smoker,January,Medical Consultation

In [12]:
print(df.dtypes)

ID                                   int64
Reason for absence                   int64
Month of absence                     int64
Day of the week                      int64
Seasons                              int64
Transportation expense             float64
Distance from Residence to Work      int64
Service time                         int64
Age                                  int64
Birth date                          object
Hire date                           object
Work load Average/day                int64
Hit target                           int64
Disciplinary failure                 int64
Education                            int64
Children                             int64
Drinker                              int64
Smoker                               int64
Pet                                  int64
Weight                               int64
Height                               int64
Body mass index                      int64
Absenteeism time in hours            int64
class                                int64
Day Name                            object
Season Name                         object
Education Level                     object
Disciplinary Failure                object
Is Drinker                          object
Is Smoker                           object
Month Name                          object
Reason Label                        object
dtype: object

In [13]:
print(df.isnull().sum())

ID                                 0
Reason for absence                 0
Month of absence                   0
Day of the week                    0
Seasons                            0
Transportation expense             1
Distance from Residence to Work    0
Service time                       0
Age                                0
Birth date                         0
Hire date                          0
Work load Average/day              0
Hit target                         0
Disciplinary failure               0
Education                          0
Children                           0
Drinker                            0
Smoker                             0
Pet                                0
Weight                             0
Height                             0
Body mass index                    0
Absenteeism time in hours          0
class                              0
Day Name                           0
Season Name                        0
Education Level                    0
Disciplinary Failure               0
Is Drinker                         0
Is Smoker                          0
Month Name                         3
Reason Label                       0
dtype: int64

In [14]:
df['Transportation expense'] = df['Transportation expense'].fillna(df['Transportation expense'].median())

df['Transportation expense'] = df['Transportation expense'].astype(int)

In [15]:
df['Month Name'] = df['Month of absence'].map({
    0: 'Not Recorded', 1: 'January', 2: 'February', 3: 'March', 4: 'April',
    5: 'May',     6: 'June',     7: 'July',       8: 'August',
    9: 'September', 10: 'October', 11: 'November', 12: 'December'
})

In [16]:
print(df.dtypes)

ID                                  int64
Reason for absence                  int64
Month of absence                    int64
Day of the week                     int64
Seasons                             int64
Transportation expense              int64
Distance from Residence to Work     int64
Service time                        int64
Age                                 int64
Birth date                         object
Hire date                          object
Work load Average/day               int64
Hit target                          int64
Disciplinary failure                int64
Education                           int64
Children                            int64
Drinker                             int64
Smoker                              int64
Pet                                 int64
Weight                              int64
Height                              int64
Body mass index                     int64
Absenteeism time in hours           int64
class                               int64
Day Name                           object
Season Name                        object
Education Level                    object
Disciplinary Failure               object
Is Drinker                         object
Is Smoker                          object
Month Name                         object
Reason Label                       object
dtype: object

In [17]:
print(df.isnull().sum())

ID                                 0
Reason for absence                 0
Month of absence                   0
Day of the week                    0
Seasons                            0
Transportation expense             0
Distance from Residence to Work    0
Service time                       0
Age                                0
Birth date                         0
Hire date                          0
Work load Average/day              0
Hit target                         0
Disciplinary failure               0
Education                          0
Children                           0
Drinker                            0
Smoker                             0
Pet                                0
Weight                             0
Height                             0
Body mass index                    0
Absenteeism time in hours          0
class                              0
Day Name                           0
Season Name                        0
Education Level                    0
Disciplinary Failure               0
Is Drinker                         0
Is Smoker                          0
Month Name                         0
Reason Label                       0
dtype: int64

In [18]:
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Birth date,...,Absenteeism time in hours,class,Day Name,Season Name,Education Level,Disciplinary Failure,Is Drinker,Is Smoker,Month Name,Reason Label
0,4,0,0,3,1,118,14,13,40,3/30/78,...,0,0,Tuesday,Summer,High School,No,Drinker,Non-Smoker,Not Recorded,Unknown
1,8,0,0,4,2,231,35,14,39,3/30/79,...,0,0,Wednesday,Autumn,High School,No,Drinker,Non-Smoker,Not Recorded,Unknown
2,35,0,0,6,3,179,45,14,53,4/2/65,...,0,0,Friday,Winter,High School,No,Non-Drinker,Non-Smoker,Not Recorded,Unknown
3,27,23,1,5,2,184,42,7,27,3/27/91,...,2,0,Thursday,Autumn,High School,No,Non-Drinker,Non-Smoker,January,Medical Consultation
4,27,23,1,5,2,184,42,7,27,3/27/91,...,2,0,Thursday,Autumn,High School,No,Non-Drinker,Non-Smoker,January,Medical Consultation

Part 4: Cleaning Survey Data

The survey data was cleaner but the same problem existed: the Likert scale scores were stored as 1 to 5 with no labels. I mapped those to readable categories like Very Unhappy, Unhappy, Meh, Happy, Very Happy. I then ran a final null check on both datasets and confirmed zero missing values before exporting.

In [19]:
work_happiness  = {1: 'Very Unhappy', 2: 'Unhappy', 3: 'Meh', 4: 'Happy',   5: 'Very Happy'}
like_scale      = {1: 'Dislike Very Much', 2: 'Dislike', 3: 'Meh', 4: 'Like', 5: 'Like Very Much'}
retention_scale = {1: 'Very Unlikely', 2: 'Unlikely', 3: 'Meh', 4: 'Likely', 5: 'Very Likely'}

df_survey['Work Happiness']     = df_survey['HI1_WorkSatisfaction'].map(work_happiness)
df_survey['Likes Manager']      = df_survey['HI2_LikesManager'].map(like_scale)
df_survey['Likes Colleagues']   = df_survey['HI3_EnjoysColleagues'].map(like_scale)
df_survey['Retention Outlook']  = df_survey['HI4_WantstoStay'].map(retention_scale)

print(df_survey['Work Happiness'].value_counts().to_string())

Work Happiness
Unhappy         305
Very Unhappy    283
Happy            80
Meh              38
Very Happy       34

In [20]:
df_survey.head()

,ID,Absenteeism time in hours,HI1_WorkSatisfaction,HI2_LikesManager,HI3_EnjoysColleagues,HI4_WantstoStay,Work Happiness,Likes Manager,Likes Colleagues,Retention Outlook
0,4,0,2,5,2,2,Unhappy,Like Very Much,Dislike,Unlikely
1,8,0,3,2,2,5,Meh,Dislike,Dislike,Very Likely
2,35,0,2,4,3,1,Unhappy,Like,Meh,Very Unlikely
3,27,2,1,4,3,2,Very Unhappy,Like,Meh,Unlikely
4,27,2,2,5,3,1,Unhappy,Like Very Much,Meh,Very Unlikely

In [21]:
print(df_survey.dtypes)

ID                            int64
Absenteeism time in hours     int64
HI1_WorkSatisfaction          int64
HI2_LikesManager              int64
HI3_EnjoysColleagues          int64
HI4_WantstoStay               int64
Work Happiness               object
Likes Manager                object
Likes Colleagues             object
Retention Outlook            object
dtype: object

In [22]:
print(df_survey.isnull().sum())

ID                           0
Absenteeism time in hours    0
HI1_WorkSatisfaction         0
HI2_LikesManager             0
HI3_EnjoysColleagues         0
HI4_WantstoStay              0
Work Happiness               0
Likes Manager                0
Likes Colleagues             0
Retention Outlook            0
dtype: int64

Part 5: Verify & Export

In [23]:
print('Absenteeism dataset')
nulls = df.isnull().sum()
print(nulls[nulls > 0].to_string() if nulls.sum() > 0 else 'No missing values')
print()

print('Survey dataset')
nulls = df_survey.isnull().sum()
print(nulls[nulls > 0].to_string() if nulls.sum() > 0 else 'No missing values')
print()

Absenteeism dataset
No missing values

Survey dataset
No missing values

In [24]:
print('Day Name values:     ', sorted(df['Day Name'].unique().tolist()))
print('Season Name values:  ', sorted(df['Season Name'].unique().tolist()))
print('Education values:    ', df['Education Level'].unique().tolist())
print('Is Drinker values:   ', df['Is Drinker'].unique().tolist())
print('Is Smoker values:    ', df['Is Smoker'].unique().tolist())
print('Month Name:    ', df['Month Name'].unique().tolist())
print('Disciplinary Failure:    ', df['Disciplinary Failure'].unique().tolist())
print('Reason Label:    ', df['Reason Label'].unique().tolist())
print()
print('Work Happiness values:', df_survey['Work Happiness'].unique().tolist())
print('Work Happiness values:', df_survey['Likes Manager'].unique().tolist())
print('Work Happiness values:', df_survey['Likes Colleagues'].unique().tolist())
print('Work Happiness values:', df_survey['Retention Outlook'].unique().tolist())

Day Name values:      ['Friday', 'Monday', 'Thursday', 'Tuesday', 'Wednesday']
Season Name values:   ['Autumn', 'Spring', 'Summer', 'Winter']
Education values:     ['High School', 'Graduate', 'Postgraduate', 'Master / Doctor']
Is Drinker values:    ['Drinker', 'Non-Drinker']
Is Smoker values:     ['Non-Smoker', 'Smoker']
Month Name:     ['Not Recorded', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
Disciplinary Failure:     ['No', 'Yes']
Reason Label:     ['Unknown', 'Medical Consultation', 'Physiotherapy', 'Dental Consultation', 'Respiratory Diseases', 'Injury & Poisoning', 'Unjustified Absence', 'Patient Follow-Up', 'Skin Diseases', 'Laboratory Examination', 'Symptoms & Abnormal Findings', 'Musculoskeletal Diseases', 'Infectious & Parasitic Diseases', 'Diseases of the Eye', 'Digestive Diseases', 'Diseases of the Ear', 'Genitourinary Diseases', 'Perinatal Conditions', 'Diseases of the Nervous System', 'Mental & Behavioural Disorders', 'Factors Influencing Health Status', 'Blood Donation', 'Pregnancy & Childbirth', 'Circulatory Diseases', 'Endocrine & Metabolic Diseases', 'Neoplasms', 'Blood & Immune Disorders', 'Congenital Malformations']

Work Happiness values: ['Unhappy', 'Meh', 'Very Unhappy', 'Happy', 'Very Happy']
Work Happiness values: ['Like Very Much', 'Dislike', 'Like', 'Meh', 'Dislike Very Much']
Work Happiness values: ['Dislike', 'Meh', 'Like Very Much', 'Like', 'Dislike Very Much']
Work Happiness values: ['Unlikely', 'Very Likely', 'Very Unlikely', 'Likely', 'Meh']

In [25]:
import os

file_export = r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files"

df.to_csv(os.path.join(file_export, 'clean_absenteeism.csv'), index=False)
print('Saved: clean_absenteeism.csv  ', f'({len(df):,} rows, {df.shape[1]} columns)')

df_survey.to_csv(os.path.join(file_export, 'clean_survey.csv'), index=False)
print('Saved: clean_survey.csv       ', f'({len(df_survey):,} rows, {df_survey.shape[1]} columns)')

Saved: clean_absenteeism.csv   (740 rows, 32 columns)
Saved: clean_survey.csv        (740 rows, 10 columns)

Part 6: Correlation

I used scipy's Pearson correlation to test two numeric variables against absenteeism (number of children and distance from work). I was deliberate about only running correlation on truly numeric continuous variables. The other variables like day of week, education, and drinking status are categorical, so I used averages for those instead, which is simpler and more appropriate.
Children came back with a correlation of +0.114 and a p-value of 0.002, which is statistically significant. Distance came back as -0.088 with a p-value of 0.016, technically significant but I was suspicious of that result because the same employee appears multiple times in the 740 rows. When I looked at the 36 unique employees instead, the p-value jumped to 0.957, meaning the relationship completely disappears. That's an important distinction between statistical significance and practical significance.

In [26]:
from scipy import stats

df_absent = pd.read_csv(r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\clean_absenteeism.csv")
df_absent.columns = df_absent.columns.str.strip()

comparisons = [
    ('Children',                         'Absenteeism time in hours'),
    ('Distance from Residence to Work',  'Absenteeism time in hours'),
]

print(f'{"Comparison":<55} {"Correlation":>12} {"P-value":>12} {"Significant?":>14}')
print('-' * 97)

for col1, col2 in comparisons:
    clean = df_absent[[col1, col2]].dropna()
    corr, pval = stats.pearsonr(clean[col1], clean[col2])
    sig = 'Yes' if pval < 0.05 else 'No'
    print(f'{col1 + " vs " + col2:<55} {corr:>+12.3f} {pval:>12.4f} {sig:>14}')

Comparison                                               Correlation      P-value   Significant?
-------------------------------------------------------------------------------------------------
Children vs Absenteeism time in hours                         +0.114       0.0019            Yes
Distance from Residence to Work vs Absenteeism time in hours       -0.088       0.0162            Yes

Part 7: Pulling Consultant Data

The consultant file had a specific structure. Each consultant occupied 3 rows: actual hours, capacity hours, and monthly variance. There was no clean single row per consultant. So I wrote a loop that stepped through every 3 rows, identified the consultant name, and pulled the rolling summary value from the actual row and the capacity row. I then dropped any rows with missing values (those corresponded to consultants Q, R, and T who didn't have complete data) and rounded everything to one decimal place before exporting to Excel for Tableau.

In [27]:
df_consult = pd.read_excel(r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\Consultant Utilization for Visualization_21.12.xlsx")
output_path  = r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\consultant_summary.xlsx"
df_consult.columns = df_consult.columns.str.strip()

rows = []
for i in range(1, len(df_consult) - 2, 3):
    consultant = str(df_consult.iloc[i]['Employee']).strip()
    if not (consultant.startswith('Consultant') or consultant.startswith('Mr')):
        continue
    
    actual_row   = df_consult.iloc[i]
    capacity_row = df_consult.iloc[i + 1]
    
    rows.append({
        'Consultant':     consultant,
        'Actual Hours':   actual_row['Rolling Summary'],
        'Capacity Hours': capacity_row['Rolling Summary'],
    })

df_summary = pd.DataFrame(rows)
print(df_summary.to_string())

df_summary.to_excel(output_path, index=False)
print('\nSaved:', output_path)

      Consultant  Actual Hours  Capacity Hours
0   Consultant A        839.00      929.000000
1   Consultant B       1225.50     1240.000000
2   Consultant C       1437.90     1240.000000
3   Consultant D       1102.80     1240.000000
4   Consultant E       1195.00     1119.000000
5   Consultant F       1218.00     1240.000000
6   Consultant G       1418.00     1240.000000
7   Consultant I       1277.00     1211.024390
8   Consultant J        820.00      929.018293
9   Consultant K       1438.51     1240.024390
10  Consultant L       1289.00     1229.024390
11  Consultant M       1002.85      805.615854
12  Consultant N        908.00     1211.024390
13  Consultant O        959.00     1240.024390
14  Consultant P       1086.60     1211.024390
15  Consultant Q           NaN             NaN
16  Consultant R           NaN             NaN
17         Mr. S        585.00      621.000000
18  Consultant T           NaN             NaN

Saved: C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\consultant_summary.xlsx

In [28]:
df_summary = df_summary.dropna(subset=['Actual Hours', 'Capacity Hours'])

df_summary['Actual Hours']   = df_summary['Actual Hours'].round(1)
df_summary['Capacity Hours'] = df_summary['Capacity Hours'].round(1)

print(df_summary.to_string())

df_summary.to_excel(output_path, index=False)
print('\nSaved')

      Consultant  Actual Hours  Capacity Hours
0   Consultant A         839.0           929.0
1   Consultant B        1225.5          1240.0
2   Consultant C        1437.9          1240.0
3   Consultant D        1102.8          1240.0
4   Consultant E        1195.0          1119.0
5   Consultant F        1218.0          1240.0
6   Consultant G        1418.0          1240.0
7   Consultant I        1277.0          1211.0
8   Consultant J         820.0           929.0
9   Consultant K        1438.5          1240.0
10  Consultant L        1289.0          1229.0
11  Consultant M        1002.8           805.6
12  Consultant N         908.0          1211.0
13  Consultant O         959.0          1240.0
14  Consultant P        1086.6          1211.0
17         Mr. S         585.0           621.0

Saved

Part 8: Verifying Employees vs Records

This was important for defending my decision to use all 740 records in the survey analysis rather than averaging down to 36. I grouped the survey data by employee ID and counted the number of unique answers each employee gave across the four survey questions. If an employee always gave the same answer, their max unique count would be 1. If it was greater than 1, their answers changed over time.

The result was 34 out of 36 employees (94%) gave different answers at some point during the year. That validated using all 740 records because each row represents a genuinely different moment in time for that employee, not just a duplicate.

In [29]:
df_clean_survey = pd.read_csv(r"C:\Users\ewlem\Documents\GitHub\Dekra Assignment\Files\clean_survey.csv")

survey_cols = ['HI1_WorkSatisfaction', 'HI2_LikesManager', 'HI3_EnjoysColleagues', 'HI4_WantstoStay']

variation = df_clean_survey.groupby('ID')[survey_cols].nunique()

changed = variation[variation.max(axis=1) > 1]

consistent = variation[variation.max(axis=1) == 1]

print(f'Total unique employees:              {df_clean_survey["ID"].nunique()}')
print(f'Employees whose answers changed:     {len(changed)}')
print(f'Employees who were always consistent:{len(consistent)}')
print()
print('Employees with changing answers:')
print(changed)

Total unique employees:              36
Employees whose answers changed:     34
Employees who were always consistent:2

Employees with changing answers:
    HI1_WorkSatisfaction  HI2_LikesManager  HI3_EnjoysColleagues  \
ID
1                      2                 3                     2
2                      2                 2                     1
3                      2                 3                     2
5                      2                 3                     2
6                      3                 4                     4
7                      4                 4                     4
8                      2                 2                     2
9                      4                 4                     3
10                     2                 3                     2
11                     5                 5                     5
12                     2                 3                     2
13                     2                 2                     2
14                     5                 5                     5
15                     2                 3                     2
16                     1                 2                     1
17                     5                 5                     5
18                     2                 3                     2
19                     2                 1                     1
20                     2                 2                     2
21                     2                 2                     2
22                     2                 3                     2
23                     4                 5                     4
24                     2                 3                     2
25                     2                 3                     2
26                     3                 3                     3
27                     2                 3                     2
28                     2                 3                     2
29                     3                 4                     4
30                     2                 3                     2
31                     2                 2                     2
32                     2                 3                     2
33                     4                 5                     5
34                     2                 3                     2
36                     2                 3                     2

    HI4_WantstoStay
ID
1                 2
2                 2
3                 2
5                 2
6                 4
7                 3
8                 2
9                 4
10                2
11                5
12                2
13                2
14                5
15                2
16                2
17                5
18                2
19                1
20                2
21                2
22                2
23                5
24                2
25                2
26                3
27                2
28                2
29                2
30                2
31                2
32                2
33                5
34                2
36                2

Part 9: Confirming unique values

I confirmed in Python that 35 of 36 employees have the exact same distance value repeated across every one of their records. Distance is a fixed attribute (it doesn't change between absence events). This proves the 740-record correlation was just repeating the same 36 distance values over and over, which is exactly why it was invalid.

In [30]:
dist_check = df.groupby('ID')['Distance from Residence to Work'].nunique()

all_same = (dist_check == 1).all()
exceptions = dist_check[dist_check > 1]

print(f'Total employees: {df["ID"].nunique()}')
print(f'Employees with same distance repeated across all records: {(dist_check == 1).sum()}')
print(f'Employees with varying distance: {len(exceptions)}')
print(f'All employees have identical distance repeated: {all_same}')

if len(exceptions) > 0:
    print(f'\nExceptions:')
    for emp_id in exceptions.index:
        values = df[df['ID'] == emp_id]['Distance from Residence to Work'].unique()
        print(f'  Employee {emp_id}: {values}')

Total employees: 36
Employees with same distance repeated across all records: 35
Employees with varying distance: 1
All employees have identical distance repeated: False

Exceptions:
  Employee 29: [15 26]